name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - main
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: astral-sh/setup-uv@v4

    - uses: pypa/cibuildwheel@v2.23
      env:
        CIBW_ENABLE: cpython-prerelease
        CIBW_ARCHS_WINDOWS: auto ARM64
        CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
          # Run auditwheel repair as normal
          auditwheel repair -w {dest_dir} {wheel} &&
          # Then, find the newly created wheel and rename it
          find {dest_dir} -name "*.whl" -print0 | xargs -0 -I {} bash -c '
            WHEEL_PATH="{}"
            WHEEL_BASENAME=$(basename "$WHEEL_PATH")
            DEST_DIR=$(dirname "$WHEEL_PATH")
            # This sed command is designed to swap the order of the two manylinux tags
            # e.g., manylinux2014_i686.manylinux_2_17_i686 -> manylinux_2_17_i686.manylinux2014_i686
            NEW_BASENAME=$(echo "$WHEEL_BASENAME" | sed -E "s/(.*)-(cp[0-9]{2,3}-cp[0-9]{2,3}-)(manylinux2014_[^.]+)\.(manylinux_2_17_[^.]+)(\.whl)/\1-\2\4.\3\5/")
            if [ "$WHEEL_BASENAME" != "$NEW_BASENAME" ]; then
              mv "$WHEEL_PATH" "$DEST_DIR/$NEW_BASENAME"
              echo "Renamed $WHEEL_BASENAME to $NEW_BASENAME"
            else
              echo "No swap needed for $WHEEL_BASENAME"
            fi
          '

    - name: Verify clean directory
      run: git diff --exit-code -- . ':!wheelhouse/'
      shell: bash
      
    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
#    if: github.event_name == 'release' && github.event.action == 'published'
    environment: pypi
    permissions:
      id-token: write
      attestations: write

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        pattern: cibw-*
        merge-multiple: true
        path: dist

#    - name: Generate artifact attestation for sdist and wheels
#      uses: actions/attest-build-provenance@v1
#      with:
#        subject-path: "dist/*"


    - name: List files in dist directory
      run: ls -al dist/

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true
